### ISSUE TITLE
Add HTTP provider

### ISSUE THREAD

**Issue by stephanebenayoun** [capsulajs/configuration-service#6]
Being able to use a served file as a provider (HTTP).
The URL should be defined using token and repository.
This configuration service will be read-only (won't implement `set` / `delete` / `deleteAll`).

**Comment by 95kach** [comment]
Is this still actual for us? @stephanebenayoun

**Comment by stephanebenayoun** [comment]
@95kach yes! It should implement the interface of ConfigurationService but partially (read only)

**Comment by stephanebenayoun** [comment]
@95kach please open a new PR to create this HTTP provider (not file provider)
